#' Plot receiver operating status.
#'
#' Plots a summary of the status data generated by \code{getOperatingStatus()}
#'
#' @param site site name
#' 
#' @param proj project name
#'
#' @param year deployment year (defaults to current year)
#' 
#' @return nothing
#'
#' Plots to the current graphics device.
#'
#' @author John Brzustowski \email{jbrzusto@@REMOVE_THIS_PART_fastmail.fm}

plotOperatingStatus = function(site, proj, year = NULL) {
    require(lubridate)
    savepar = par()
    if (is.null(year))
        year = year(Sys.time())
    
    a = getOperatingStatus(site, proj, year)

    ## filter out data more than 3 years from start date (eliminate wonky GPS records) and before
    ## the start date
    start_ts = ymd(sprintf("%d-01-01", year))
    a$files.per.hour = subset(a$files.per.hour, ts >= start_ts & ts <= start_ts + 3 * 365.25 * 24 * 3600)
    timerange = range(a$files.per.hour$ts)
    
    par(mar=c(7,4,4,2) + 0.1)
    plot(trunc(a$files.per.hour$ts, "day"),
         hour(a$files.per.hour$ts),
         pch = 0,
         col = "green",
         ylim = c(24, 0),
         main = c(sprintf("Status of Receiver at '%s' Site of '%s' Project - %d", site, proj, year),
             sprintf("%d reboots during period shown", a$num.boots)),
         xlab = "",
         ylab = "Hour of Day (GMT)",
         sub = c("Date (GMT)\nSquares are hours with data recorded; when filled, GPS was working.\nBlack x indicates a reboot.  Dashed black line is reboot count.")
         )

    points(trunc(a$gps$ts, "day"), hour(a$gps$ts), pch=15, col="green")
    abline(v = seq(from = trunc(timerange[1], "days"), to = trunc(timerange[2], "days"), by = 24 * 3600), lty=3, col="gray")
    rb = a$files.per.hour$ts[which(c(FALSE, diff(a$files.per.hour$bootnum) > 0))]
    points(rb, hour(rb), pch="x", col="black")
    points(a$files.per.hour$ts, 23 - a$files.per.hour$bootnum %% 24, type="s", lty=3, col="black")
    ##abline(v=rb, lty=3, col="red")
    par(savepar)
}

