#' Plot receiver operating status.
#'
#' Plots a summary of the status data generated by \code{getOperatingStatus()}
#'
#' @param site site name
#' 
#' @param proj project name
#'
#' @param year deployment year (defaults to current year)
#' 
#' @return nothing
#'
#' Plots to the current graphics device.
#'
#' @author John Brzustowski \email{jbrzusto@@REMOVE_THIS_PART_fastmail.fm}

plotOperatingStatus = function(site, proj, year = lubridate::year(Sys.time())) {
    library(lubridate)
    a = getOperatingStatus(site, proj, year)

    ## filter out data more than 3 years from start date (eliminate wonky GPS records) and before
    ## the start date
    start_ts = ymd(sprintf("%d-01-01", year))
    a$files.per.hour = subset(a$files.per.hour, ts >= start_ts & ts <= start_ts + 3 * 365.25 * 24 * 3600)
    timerange = range(a$files.per.hour$ts)
    
    xx = trunc(a$files.per.hour$ts, "day")
    yy = hour(a$files.per.hour$ts)
    
    plot(xx,
         yy,
         pch = ' ',
         col = "green",
         ylim = c(0, 24),
         main = c(sprintf("%d %s %s", year, proj, site), "Receiver status based on raw data file timestamps and GPS fixes"),
         xlab = "",
         ylab = "Hour of Day (GMT)",
         sub = sprintf("Date (GMT; %d onwards)\n Green: Writing Files and GPS working;    Yellow: Writing Files but GPS stuck;    Red: Not Writing Files\nBlack *: reboot;   Black line: reboot count, wrapping at 24; period shown had %d reboots"
             , year, a$num.boots)
         )

    rect (min(xx), min(yy), max(xx), max(yy)+1, col="#ff4040")
    rect(xx, yy, xx + 3600*24, yy + 1,
        col="yellow", border="yellow")
     
    xx = trunc(a$gps$ts, "day")
    yy = hour(a$gps$ts)
    rect(xx, yy, xx + 24*3600, yy + 1, col="green", border="green")
    abline(v = seq(from = trunc(timerange[1], "days"), to = trunc(timerange[2], "days"), by = 24 * 3600), lty=3, col="gray")
    rb = a$files.per.hour$ts[which(c(FALSE, diff(a$files.per.hour$bootnum) > 0))]
    points(trunc(rb, "day")+12*3600, hour(rb), pch="*", col="black")
    points(a$files.per.hour$ts, a$files.per.hour$bootnum %% 24, type="s", col="black")
}

